server.port=8888

# ====================== BASE DE DONNÉES POSTGRESQL ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=user1
spring.datasource.password=user1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Optionnel : joli affichage des logs
spring.output.ansi.enabled=always